# Generated by Django 4.2.25 on 2025-12-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(help_text='Exxample 0+100 ext...', max_length=50)),
                ('backsight', models.FloatField(blank=True, null=True)),
                ('foresight', models.FloatField(blank=True, null=True)),
                ('bwd_backsight', models.FloatField(blank=True, null=True)),
                ('bwd_foresight', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('distance_bwd', models.FloatField(blank=True, null=True)),
                ('distance_avg', models.FloatField(blank=True, null=True)),
                ('design_elevation', models.FloatField(blank=True, help_text='Elevasi Rencana', null=True)),
                ('cut_volume', models.FloatField(default=0.0, help_text='Volume Galian (m3)')),
                ('fill_volume', models.FloatField(default=0.0, help_text='Volume Timbunan (m3)')),
                ('height_difference', models.FloatField(blank=True, null=True)),
                ('height_difference_bwd', models.FloatField(blank=True, null=True)),
                ('height_difference_avg', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(help_text='Elevasi (AMSL) hasil hitungan')),
                ('correction', models.FloatField(blank=True, null=True)),
                ('cumulative_distance', models.FloatField()),
                ('status', models.CharField(help_text='RISE, FALL, atau FLAT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey_type', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10)),
                ('initial_elevation', models.FloatField(default=100.0, help_text='Elevasi (Z) awal dari titik pertama (dari init_amsl)')),
                ('purpose', models.CharField(blank=True, help_text='Tujuan survei (dari purpose)', max_length=255)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='IN_PROGRESS', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(help_text='Example: 0+000, 0+100, dst.', max_length=50)),
                ('bs_top', models.FloatField(blank=True, help_text='Benang Atas (BS)', null=True)),
                ('bs_mid', models.FloatField(blank=True, help_text='Benang Tengah (BS) - WAJIB', null=True)),
                ('bs_bot', models.FloatField(blank=True, help_text='Benang Bawah (BS)', null=True)),
                ('fs_top', models.FloatField(blank=True, help_text='Benang Atas (FS)', null=True)),
                ('fs_mid', models.FloatField(blank=True, help_text='Benang Tengah (FS) - WAJIB', null=True)),
                ('fs_bot', models.FloatField(blank=True, help_text='Benang Bawah (FS)', null=True)),
                ('bwd_bs_top', models.FloatField(blank=True, null=True)),
                ('bwd_bs_mid', models.FloatField(blank=True, null=True)),
                ('bwd_bs_bot', models.FloatField(blank=True, null=True)),
                ('bwd_fs_top', models.FloatField(blank=True, null=True)),
                ('bwd_fs_mid', models.FloatField(blank=True, null=True)),
                ('bwd_fs_bot', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, help_text='Jarak Datar (Optis atau Manual)', null=True)),
                ('distance_bwd', models.FloatField(blank=True, help_text='Jarak Datar (Optis atau Manual)', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveling_data', to='survey.project')),
            ],
        ),
        migrations.CreateModel(
            name='CrossSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label titik, misal: A, B, C, D', max_length=50)),
                ('distance', models.FloatField(help_text='Jarak dari As (m). Kiri (-), Kanan (+)')),
                ('top', models.FloatField(blank=True, help_text='Benang Atas', null=True)),
                ('mid', models.FloatField(help_text='Benang Tengah (Wajib)')),
                ('bot', models.FloatField(blank=True, help_text='Benang Bawah', null=True)),
                ('elevation', models.FloatField(blank=True, help_text='Elevasi Titik', null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrossSection', to='survey.project')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_section', to='survey.calculatedresult')),
            ],
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='survey.project'),
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='survey.project')),
            ],
        ),
    ]
