# Generated by Django 4.2.25 on 2025-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosssection',
            name='height_difference',
            field=models.FloatField(blank=True, help_text='height difference', null=True),
        ),
    ]
