# Generated by Django 4.2.25 on 2025-12-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_crosssection_height_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosssection',
            name='project',
        ),
    ]
