# Generated by Django 4.2.25 on 2025-12-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_crosssection_source_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosssection',
            name='source_row',
        ),
        migrations.AddField(
            model_name='calculatedresult',
            name='source_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_result', to='survey.levelingdata'),
        ),
    ]
