# Generated by Django 4.2.25 on 2026-02-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_crosssection_source_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lane_slope',
            field=models.FloatField(default=-2.0, help_text='Kemiringan lajur utama (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='lane_width',
            field=models.FloatField(default=3.5, help_text='Lebar lajur utama (m)'),
        ),
        migrations.AddField(
            model_name='project',
            name='shoulder_slope',
            field=models.FloatField(default=-4.0, help_text='Kemiringan bahu jalan (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='shoulder_width',
            field=models.FloatField(default=1.5, help_text='Lebar bahu jalan (m)'),
        ),
    ]
